### ISSUE TITLE
Build does not work without errors with current version of Ubuntu like 22.04.3

### ISSUE THREAD

**Issue by nemihome** [HSAnet/reverse-traceroute#17]
Error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
poetry 1.1.12 requires keyring<22.0.0,>=21.2.0; python_version >= "3.6" and python_version < "4.0", but you have keyring 23.5.0 which is incompatible.
poetry 1.1.12 requires packaging<21.0,>=20.4, but you have packaging 21.3 which is incompatible.
```

I only made a short test up to now but the client seems to work for the first test at least in forward direction.

In reverse direction I'm getting:

```
Virtual-Machine:~/reverse-traceroute/client$ sudo augsburg-traceroute reverse udp multipath d001.eu.prod.t300.ter.int.amazonvideo.com
[sudo] password for tim: 
INFO:src.client:Determined traceroute target: 52.84.106.102
ERROR:src.client:The target did not respond to the reverse traceroute probe.
Virtual-Machine:~/reverse-traceroute/client$ sudo augsburg-traceroute reverse tcp multipath d001.eu.prod.t300.ter.int.amazonvideo.com
INFO:src.client:Determined traceroute target: 52.84.106.84
ERROR:src.client:The target did not respond to the reverse traceroute probe.
```

But that seems to be something connected to the amazon servers.

**Comment by vhein99** [comment]
Hi,
sorry for the late response, I was on vacation :)
The error you are getting in the reverse direction occurs because the target in question does not run the reverse-traceroute server.
The publicly available server endpoints are listed inside the [ENDPOINTS](../blob/master/ENDPOINTS) file,
you can try to run a reverse trace against one of those.

It might be necessary to better highlight the fact that the client relies on the target running the server software
to trace in the reverse direction, thanks for pointing that out.
