### ISSUE TITLE
Improvement: Add a flag to transmit without further question

### ISSUE THREAD

**Issue by agbcix** [HSAnet/reverse-traceroute#3]
I understand that using `--transmit` has some security implications. Thus there is a prompt to ensure that the user needs to make an informed decision.

I see a use case for some kind of batch mode. I.e. someone who doesn't want to be prompted for approval.

I can imagine to have some `--force-transmit` or `--transmit -y` flag.

Using `echo "yes" | augsburg-traceroute --transmit` will do the same -- which may be considered as argument pro and contra at the same time.

**Comment by vhein99** [comment]
I like the idea of implementing a switch for proceeding without further input,
it certainly makes the program a better fit for use in automated scripts.

I personally like the idea of a generic `-y` switch,
should more prompts be added to the client in the future (which is unlikely, but still possible)
we can handle them all with the single switch, instead of implementing a specific force flag like `--force-transmit`
for each of those prompts.

**Comment by vhein99** [comment]
Requested improvement implemented by commit ea828f6badd36eb8b984dbc94eaf1628b135a251.  
The user can now specify the -y / --assume-yes switch to run the program in batch mode.
